// Licence file C:\Users\julio\OneDrive\Documentos\ReversePOCO.txt not found.
// Please obtain your licence file at www.ReversePOCO.co.uk, and place it in your documents folder shown above.
// Defaulting to Trial version.
// <auto-generated>
// ReSharper disable All

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlTypes;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace GameJornadaQuest.Server.Data
{
    #region Database context interface

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public interface Idb_jornadaquest : IDisposable
    {
        DbSet<ItensRodada> ItensRodadas { get; set; } // itens_rodada
        DbSet<ItensRodadaClick> ItensRodadaClicks { get; set; } // itens_rodada_clicks
        DbSet<Pessoa> Pessoas { get; set; } // pessoas
        DbSet<Rodada> Rodadas { get; set; } // rodadas
        DbSet<StatusRodada> StatusRodadas { get; set; } // status_rodada

        int SaveChanges();
        int SaveChanges(bool acceptAllChangesOnSuccess);
        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken));
        Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken));
        DatabaseFacade Database { get; }
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        EntityEntry Add(object entity);
        EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class;
        Task AddRangeAsync(params object[] entities);
        Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default);
        ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class;
        ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default);
        void AddRange(IEnumerable<object> entities);
        void AddRange(params object[] entities);

        EntityEntry Attach(object entity);
        EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class;
        void AttachRange(IEnumerable<object> entities);
        void AttachRange(params object[] entities);

        EntityEntry Entry(object entity);
        EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;

        TEntity Find<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class;
        ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class;
        ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken);
        ValueTask<object> FindAsync(Type entityType, params object[] keyValues);
        object Find(Type entityType, params object[] keyValues);

        EntityEntry Remove(object entity);
        EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class;
        void RemoveRange(IEnumerable<object> entities);
        void RemoveRange(params object[] entities);

        EntityEntry Update(object entity);
        EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class;
        void UpdateRange(IEnumerable<object> entities);
        void UpdateRange(params object[] entities);

        IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression);
    }

    #endregion

    #region Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class db_jornadaquest : DbContext, Idb_jornadaquest
    {
        public db_jornadaquest()
        {
        }

        public db_jornadaquest(DbContextOptions<db_jornadaquest> options)
            : base(options)
        {
        }

        public DbSet<ItensRodada> ItensRodadas { get; set; } // itens_rodada
        public DbSet<ItensRodadaClick> ItensRodadaClicks { get; set; } // itens_rodada_clicks
        public DbSet<Pessoa> Pessoas { get; set; } // pessoas
        public DbSet<Rodada> Rodadas { get; set; } // rodadas
        public DbSet<StatusRodada> StatusRodadas { get; set; } // status_rodada

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=localhost;Initial Catalog=db_jornadaquest;Integrated Security=True;MultipleActiveResultSets=True;Encrypt=false;TrustServerCertificate=true");
            }
        }

        public bool IsSqlParameterNull(SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == DBNull.Value);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new ItensRodadaConfiguration());
            modelBuilder.ApplyConfiguration(new ItensRodadaClickConfiguration());
            modelBuilder.ApplyConfiguration(new PessoaConfiguration());
            modelBuilder.ApplyConfiguration(new RodadaConfiguration());
            modelBuilder.ApplyConfiguration(new StatusRodadaConfiguration());
        }

    }

    #endregion

    #region Database context factory

    public class db_jornadaquestFactory : IDesignTimeDbContextFactory<db_jornadaquest>
    {
        public db_jornadaquest CreateDbContext(string[] args)
        {
            return new db_jornadaquest();
        }
    }

    #endregion

    #region Fake Database context

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    public class Fakedb_jornadaquest : Idb_jornadaquest
    {
        public DbSet<ItensRodada> ItensRodadas { get; set; } // itens_rodada
        public DbSet<ItensRodadaClick> ItensRodadaClicks { get; set; } // itens_rodada_clicks
        public DbSet<Pessoa> Pessoas { get; set; } // pessoas
        public DbSet<Rodada> Rodadas { get; set; } // rodadas
        public DbSet<StatusRodada> StatusRodadas { get; set; } // status_rodada

        public Fakedb_jornadaquest()
        {
            _database = new FakeDatabaseFacade(new db_jornadaquest());

            ItensRodadas = new FakeDbSet<ItensRodada>("IdItemRodada");
            ItensRodadaClicks = new FakeDbSet<ItensRodadaClick>("IdItemRodadaClick");
            Pessoas = new FakeDbSet<Pessoa>("IdPessoa");
            Rodadas = new FakeDbSet<Rodada>("IdRodada");
            StatusRodadas = new FakeDbSet<StatusRodada>("IdStatusRodada");

        }

        public int SaveChangesCount { get; private set; }
        public virtual int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public virtual int SaveChanges(bool acceptAllChangesOnSuccess)
        {
            return SaveChanges();
        }

        public virtual Task<int> SaveChangesAsync(CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }
        public virtual Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return Task<int>.Factory.StartNew(x => 1, acceptAllChangesOnSuccess, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private DatabaseFacade _database;
        public DatabaseFacade Database { get { return _database; } }

        public DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new NotImplementedException();
        }

        public override string ToString()
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Add(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Add<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual Task AddRangeAsync(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual async Task AddRangeAsync(IEnumerable<object> entities, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry<TEntity>> AddAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default) where TEntity : class
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual async ValueTask<EntityEntry> AddAsync(object entity, CancellationToken cancellationToken = default)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        public virtual void AddRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AddRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Attach(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Attach<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void AttachRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Entry(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual TEntity Find<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(object[] keyValues, CancellationToken cancellationToken) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<TEntity> FindAsync<TEntity>(params object[] keyValues) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, object[] keyValues, CancellationToken cancellationToken)
        {
            throw new NotImplementedException();
        }

        public virtual ValueTask<object> FindAsync(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual object Find(Type entityType, params object[] keyValues)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Remove(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Remove<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void RemoveRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry Update(object entity)
        {
            throw new NotImplementedException();
        }

        public virtual EntityEntry<TEntity> Update<TEntity>(TEntity entity) where TEntity : class
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(IEnumerable<object> entities)
        {
            throw new NotImplementedException();
        }

        public virtual void UpdateRange(params object[] entities)
        {
            throw new NotImplementedException();
        }

        public virtual IQueryable<TResult> FromExpression<TResult> (Expression<Func<IQueryable<TResult>>> expression)
        {
            throw new NotImplementedException();
        }

    }

    #endregion

    #region Fake DbSet

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    public class FakeDbSet<TEntity> :
        DbSet<TEntity>,
        IQueryable<TEntity>,
        IAsyncEnumerable<TEntity>,
        IListSource,
        IResettableService
        where TEntity : class
    {
        private readonly PropertyInfo[] _primaryKeys;
        private ObservableCollection<TEntity> _data;
        private IQueryable _query;
        public override IEntityType EntityType { get; }

        public FakeDbSet()
        {
            _primaryKeys = null;
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data        = new ObservableCollection<TEntity>();
            _query       = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override ValueTask<TEntity> FindAsync(object[] keyValues, CancellationToken cancellationToken)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken));
        }

        public override ValueTask<TEntity> FindAsync(params object[] keyValues)
        {
            return new ValueTask<TEntity>(Task<TEntity>.Factory.StartNew(() => Find(keyValues)));
        }

        public override EntityEntry<TEntity> Add(TEntity entity)
        {
            _data.Add(entity);
            return null;
        }

        public override ValueTask<EntityEntry<TEntity>> AddAsync(TEntity entity, CancellationToken cancellationToken = default)
        {
            return new ValueTask<EntityEntry<TEntity>>(Task<EntityEntry<TEntity>>.Factory.StartNew(() => Add(entity), cancellationToken));
        }

        public override void AddRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override void AddRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities)
                _data.Add(entity);
        }

        public override Task AddRangeAsync(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities));
        }

        public override Task AddRangeAsync(IEnumerable<TEntity> entities, CancellationToken cancellationToken = default)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            return Task.Factory.StartNew(() => AddRange(entities), cancellationToken);
        }

        public override EntityEntry<TEntity> Attach(TEntity entity)
        {
            if (entity == null) throw new ArgumentNullException("entity");
            return Add(entity);
        }

        public override void AttachRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override void AttachRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            AddRange(entities);
        }

        public override EntityEntry<TEntity> Remove(TEntity entity)
        {
            _data.Remove(entity);
            return null;
        }

        public override void RemoveRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            foreach (var entity in entities.ToList())
                _data.Remove(entity);
        }

        public override void RemoveRange(IEnumerable<TEntity> entities)
        {
            RemoveRange(entities.ToArray());
        }

        public override EntityEntry<TEntity> Update(TEntity entity)
        {
            _data.Remove(entity);
            _data.Add(entity);
            return null;
        }

        public override void UpdateRange(params TEntity[] entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            RemoveRange(entities);
            AddRange(entities);
        }

        public override void UpdateRange(IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var array = entities.ToArray();        RemoveRange(array);
            AddRange(array);
        }

        bool IListSource.ContainsListCollection => true;

        public IList GetList()
        {
            return _data;
        }

        IList IListSource.GetList()
        {
            return _data;
        }

        Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_data); }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        IEnumerator<TEntity> IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        public override IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }

        public void ResetState()
        {
            _data  = new ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public Task ResetStateAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.Factory.StartNew(() => ResetState());
        }
    }

    public class FakeDbAsyncQueryProvider<TEntity> : FakeQueryProvider<TEntity>, IAsyncEnumerable<TEntity>, IAsyncQueryProvider
    {
        public FakeDbAsyncQueryProvider(Expression expression) : base(expression)
        {
        }

        public FakeDbAsyncQueryProvider(IEnumerable<TEntity> enumerable) : base(enumerable)
        {
        }

        public TResult ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
        {
            var expectedResultType = typeof(TResult).GetGenericArguments()[0];
            var executionResult = typeof(IQueryProvider)
                .GetMethods()
                .First(method => method.Name == nameof(IQueryProvider.Execute) && method.IsGenericMethod)
                .MakeGenericMethod(expectedResultType)
                .Invoke(this, new object[] { expression });

            return (TResult) typeof(Task).GetMethod(nameof(Task.FromResult))
                ?.MakeGenericMethod(expectedResultType)
                .Invoke(null, new[] { executionResult });
        }

        public IAsyncEnumerator<TEntity> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new FakeDbAsyncEnumerator<TEntity>(this.AsEnumerable().GetEnumerator());
        }
    }

    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, IAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(IEnumerable<T> enumerable)
            : base(enumerable)
        {
        }

        public FakeDbAsyncEnumerable(Expression expression)
            : base(expression)
        {
        }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = new CancellationToken())
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        IAsyncEnumerator<T> IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
        {
            return GetAsyncEnumerator(cancellationToken);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.AsEnumerable().GetEnumerator();
        }
    }

    public class FakeDbAsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private readonly IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        public ValueTask<bool> MoveNextAsync()
        {
            return new ValueTask<bool>(_inner.MoveNext());
        }

        public ValueTask DisposeAsync()
        {
            _inner.Dispose();
            return new ValueTask(Task.CompletedTask);
        }
    }

    public abstract class FakeQueryProvider<T> : IOrderedQueryable<T>, IQueryProvider
    {
        private IEnumerable<T> _enumerable;

        protected FakeQueryProvider(Expression expression)
        {
            Expression = expression;
        }

        protected FakeQueryProvider(IEnumerable<T> enumerable)
        {
            _enumerable = enumerable;
            Expression = enumerable.AsQueryable().Expression;
        }

        public IQueryable CreateQuery(Expression expression)
        {
            if (expression is MethodCallExpression m)
            {
                var resultType = m.Method.ReturnType; // it should be IQueryable<T>
                var tElement = resultType.GetGenericArguments().First();
                return (IQueryable) CreateInstance(tElement, expression);
            }

            return CreateQuery<T>(expression);
        }

        public IQueryable<TEntity> CreateQuery<TEntity>(Expression expression)
        {
            return (IQueryable<TEntity>) CreateInstance(typeof(TEntity), expression);
        }

        private object CreateInstance(Type tElement, Expression expression)
        {
            var queryType = GetType().GetGenericTypeDefinition().MakeGenericType(tElement);
            return Activator.CreateInstance(queryType, expression);
        }

        public object Execute(Expression expression)
        {
            return CompileExpressionItem<object>(expression);
        }

        public TResult Execute<TResult>(Expression expression)
        {
            return CompileExpressionItem<TResult>(expression);
        }

        IEnumerator<T> IEnumerable<T>.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            if (_enumerable == null) _enumerable = CompileExpressionItem<IEnumerable<T>>(Expression);
            return _enumerable.GetEnumerator();
        }

        public Type ElementType => typeof(T);

        public Expression Expression { get; }

        public IQueryProvider Provider => this;

        private static TResult CompileExpressionItem<TResult>(Expression expression)
        {
            var visitor = new FakeExpressionVisitor();
            var body = visitor.Visit(expression);
            var f = Expression.Lambda<Func<TResult>>(body ?? throw new InvalidOperationException(string.Format("{0} is null", nameof(body))), (IEnumerable<ParameterExpression>) null);
            return f.Compile()();
        }
    }

    public class FakeExpressionVisitor : ExpressionVisitor
    {
    }

    public class FakeDatabaseFacade : DatabaseFacade
    {
        public FakeDatabaseFacade(DbContext context) : base(context)
        {
        }

        public override bool EnsureCreated()
        {
            return true;
        }

        public override Task<bool> EnsureCreatedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureCreated());
        }

        public override bool EnsureDeleted()
        {
            return true;
        }

        public override Task<bool> EnsureDeletedAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(EnsureDeleted());
        }

        public override bool CanConnect()
        {
            return true;
        }

        public override Task<bool> CanConnectAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(CanConnect());
        }

        public override IDbContextTransaction BeginTransaction()
        {
            return new FakeDbContextTransaction();
        }

        public override Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.FromResult(BeginTransaction());
        }

        public override void CommitTransaction()
        {
        }

        public override Task CommitTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override void RollbackTransaction()
        {
        }

        public override Task RollbackTransactionAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            return Task.CompletedTask;
        }

        public override IExecutionStrategy CreateExecutionStrategy()
        {
            return null;
        }

        public override string ToString()
        {
            return string.Empty;
        }
    }

    public class FakeDbContextTransaction : IDbContextTransaction
    {
        public Guid TransactionId => Guid.NewGuid();
        public void Commit() { }
        public void Rollback() { }
        public Task CommitAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public Task RollbackAsync(CancellationToken cancellationToken = new CancellationToken()) => Task.CompletedTask;
        public void Dispose() { }
        public ValueTask DisposeAsync() => default;
    }

    #endregion

    #region POCO classes

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // itens_rodada
    public class ItensRodada
    {
        public int IdItemRodada { get; set; } // id_item_rodada (Primary key)
        public int IdRodada { get; set; } // id_rodada
        public int IdPessoa { get; set; } // id_pessoa
        public Guid? UiConexao { get; set; } // ui_conexao
        public bool BoAtivo { get; set; } // bo_ativo
        public int NrClicks { get; set; } // nr_clicks

        // Reverse navigation

        /// <summary>
        /// Child ItensRodadaClicks where [itens_rodada_clicks].[id_item_rodada] point to this entity (FK_itens_rodada_clicks_itens_rodada)
        /// </summary>
        public ICollection<ItensRodadaClick> ItensRodadaClicks { get; set; } // itens_rodada_clicks.FK_itens_rodada_clicks_itens_rodada

        // Foreign keys

        /// <summary>
        /// Parent Pessoa pointed by [itens_rodada].([IdPessoa]) (FK_itens_rodada_pessoas)
        /// </summary>
        public Pessoa Pessoa { get; set; } // FK_itens_rodada_pessoas

        /// <summary>
        /// Parent Rodada pointed by [itens_rodada].([IdRodada]) (FK_itens_rodada_rodadas)
        /// </summary>
        public Rodada Rodada { get; set; } // FK_itens_rodada_rodadas

        public ItensRodada()
        {
            BoAtivo = false;
            NrClicks = 0;
            ItensRodadaClicks = new List<ItensRodadaClick>();
        }
    }

    // itens_rodada_clicks
    public class ItensRodadaClick
    {
        public int IdItemRodadaClick { get; set; } // id_item_rodada_click (Primary key)
        public int IdItemRodada { get; set; } // id_item_rodada
        public DateTime DtItemClick { get; set; } // dt_item_click

        // Foreign keys

        /// <summary>
        /// Parent ItensRodada pointed by [itens_rodada_clicks].([IdItemRodada]) (FK_itens_rodada_clicks_itens_rodada)
        /// </summary>
        public ItensRodada ItensRodada { get; set; } // FK_itens_rodada_clicks_itens_rodada
    }

    // pessoas
    public class Pessoa
    {
        public int IdPessoa { get; set; } // id_pessoa (Primary key)
        public string NmPessoa { get; set; } // nm_pessoa (length: 80)

        // Reverse navigation

        /// <summary>
        /// Child ItensRodadas where [itens_rodada].[id_pessoa] point to this entity (FK_itens_rodada_pessoas)
        /// </summary>
        public ICollection<ItensRodada> ItensRodadas { get; set; } // itens_rodada.FK_itens_rodada_pessoas

        /// <summary>
        /// Child Rodadas where [rodadas].[id_pessoa] point to this entity (FK_rodadas_pessoas)
        /// </summary>
        public ICollection<Rodada> Rodadas { get; set; } // rodadas.FK_rodadas_pessoas

        public Pessoa()
        {
            ItensRodadas = new List<ItensRodada>();
            Rodadas = new List<Rodada>();
        }
    }

    // rodadas
    public class Rodada
    {
        public int IdRodada { get; set; } // id_rodada (Primary key)
        public int? IdPessoa { get; set; } // id_pessoa
        public int IdStatusRodada { get; set; } // id_status_rodada
        public int NrLimiteClickMinutos { get; set; } // nr_limite_click_minutos
        public DateTime DtInicioRodada { get; set; } // dt_inicio_rodada
        public DateTime? DtInicioFim { get; set; } // dt_inicio_fim

        // Reverse navigation

        /// <summary>
        /// Child ItensRodadas where [itens_rodada].[id_rodada] point to this entity (FK_itens_rodada_rodadas)
        /// </summary>
        public ICollection<ItensRodada> ItensRodadas { get; set; } // itens_rodada.FK_itens_rodada_rodadas

        // Foreign keys

        /// <summary>
        /// Parent Pessoa pointed by [rodadas].([IdPessoa]) (FK_rodadas_pessoas)
        /// </summary>
        public Pessoa Pessoa { get; set; } // FK_rodadas_pessoas

        /// <summary>
        /// Parent StatusRodada pointed by [rodadas].([IdStatusRodada]) (FK_rodadas_status_rodada)
        /// </summary>
        public StatusRodada StatusRodada { get; set; } // FK_rodadas_status_rodada

        public Rodada()
        {
            IdStatusRodada = 1;
            NrLimiteClickMinutos = 30;
            DtInicioRodada = DateTime.Now;
            ItensRodadas = new List<ItensRodada>();
        }
    }

    // status_rodada
    public class StatusRodada
    {
        public int IdStatusRodada { get; set; } // id_status_rodada (Primary key)
        public string NmStatusRodada { get; set; } // nm_status_rodada (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Rodadas where [rodadas].[id_status_rodada] point to this entity (FK_rodadas_status_rodada)
        /// </summary>
        public ICollection<Rodada> Rodadas { get; set; } // rodadas.FK_rodadas_status_rodada

        public StatusRodada()
        {
            Rodadas = new List<Rodada>();
        }
    }


    #endregion

    #region POCO Configuration

    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // itens_rodada
    public class ItensRodadaConfiguration : IEntityTypeConfiguration<ItensRodada>
    {
        public void Configure(EntityTypeBuilder<ItensRodada> builder)
        {
            builder.ToTable("itens_rodada", "dbo");
            builder.HasKey(x => x.IdItemRodada).HasName("PK__itens_ro__5181E15194E1EFA2").IsClustered();

            builder.Property(x => x.IdItemRodada).HasColumnName(@"id_item_rodada").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IdRodada).HasColumnName(@"id_rodada").HasColumnType("int").IsRequired();
            builder.Property(x => x.IdPessoa).HasColumnName(@"id_pessoa").HasColumnType("int").IsRequired();
            builder.Property(x => x.UiConexao).HasColumnName(@"ui_conexao").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.BoAtivo).HasColumnName(@"bo_ativo").HasColumnType("bit").IsRequired();
            builder.Property(x => x.NrClicks).HasColumnName(@"nr_clicks").HasColumnType("int").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Pessoa).WithMany(b => b.ItensRodadas).HasForeignKey(c => c.IdPessoa).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_itens_rodada_pessoas");
            builder.HasOne(a => a.Rodada).WithMany(b => b.ItensRodadas).HasForeignKey(c => c.IdRodada).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_itens_rodada_rodadas");
        }
    }

    // itens_rodada_clicks
    public class ItensRodadaClickConfiguration : IEntityTypeConfiguration<ItensRodadaClick>
    {
        public void Configure(EntityTypeBuilder<ItensRodadaClick> builder)
        {
            builder.ToTable("itens_rodada_clicks", "dbo");
            builder.HasKey(x => x.IdItemRodadaClick).HasName("PK__itens_ro__6CEEEE8D9F726BCF").IsClustered();

            builder.Property(x => x.IdItemRodadaClick).HasColumnName(@"id_item_rodada_click").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IdItemRodada).HasColumnName(@"id_item_rodada").HasColumnType("int").IsRequired();
            builder.Property(x => x.DtItemClick).HasColumnName(@"dt_item_click").HasColumnType("datetime").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.ItensRodada).WithMany(b => b.ItensRodadaClicks).HasForeignKey(c => c.IdItemRodada).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_itens_rodada_clicks_itens_rodada");

            builder.HasIndex(x => new { x.IdItemRodada, x.DtItemClick }).HasDatabaseName("UN_itens_rodada_clicks").IsUnique();
        }
    }

    // pessoas
    public class PessoaConfiguration : IEntityTypeConfiguration<Pessoa>
    {
        public void Configure(EntityTypeBuilder<Pessoa> builder)
        {
            builder.ToTable("pessoas", "dbo");
            builder.HasKey(x => x.IdPessoa).HasName("PK__pessoas__C22153072C333248").IsClustered();

            builder.Property(x => x.IdPessoa).HasColumnName(@"id_pessoa").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.NmPessoa).HasColumnName(@"nm_pessoa").HasColumnType("varchar(80)").IsRequired().IsUnicode(false).HasMaxLength(80);

            builder.HasIndex(x => x.NmPessoa).HasDatabaseName("UN_pessoas").IsUnique();
        }
    }

    // rodadas
    public class RodadaConfiguration : IEntityTypeConfiguration<Rodada>
    {
        public void Configure(EntityTypeBuilder<Rodada> builder)
        {
            builder.ToTable("rodadas", "dbo");
            builder.HasKey(x => x.IdRodada).HasName("PK__rodadas__E69087046ED6F231").IsClustered();

            builder.Property(x => x.IdRodada).HasColumnName(@"id_rodada").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IdPessoa).HasColumnName(@"id_pessoa").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.IdStatusRodada).HasColumnName(@"id_status_rodada").HasColumnType("int").IsRequired();
            builder.Property(x => x.NrLimiteClickMinutos).HasColumnName(@"nr_limite_click_minutos").HasColumnType("int").IsRequired();
            builder.Property(x => x.DtInicioRodada).HasColumnName(@"dt_inicio_rodada").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.DtInicioFim).HasColumnName(@"dt_inicio_fim").HasColumnType("datetime").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Pessoa).WithMany(b => b.Rodadas).HasForeignKey(c => c.IdPessoa).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_rodadas_pessoas");
            builder.HasOne(a => a.StatusRodada).WithMany(b => b.Rodadas).HasForeignKey(c => c.IdStatusRodada).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_rodadas_status_rodada");
        }
    }

    // status_rodada
    public class StatusRodadaConfiguration : IEntityTypeConfiguration<StatusRodada>
    {
        public void Configure(EntityTypeBuilder<StatusRodada> builder)
        {
            builder.ToTable("status_rodada", "dbo");
            builder.HasKey(x => x.IdStatusRodada).HasName("PK__status_r__CC82E2E9EB038C7B").IsClustered();

            builder.Property(x => x.IdStatusRodada).HasColumnName(@"id_status_rodada").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.NmStatusRodada).HasColumnName(@"nm_status_rodada").HasColumnType("varchar(50)").IsRequired().IsUnicode(false).HasMaxLength(50);

            builder.HasIndex(x => x.NmStatusRodada).HasDatabaseName("UN_status_rodada").IsUnique();
        }
    }


    #endregion

}
// </auto-generated>
